import { Eye, EyeOff, Landmark, Link2, Plus, ShieldCheck, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { PageHeader } from "../components/PageHeader.jsx";
import { apiGet, apiPost } from "../lib/api.js";

const emptyAccount = { nickname: "", institutionName: "", accountType: "savings", maskedNumber: "", balanceRupees: "", sharingScope: "only_me", notes: "" };

export function FinancialAccountsPage() {
  const familyId = localStorage.getItem("nyasa_family_id"); const [accounts,setAccounts]=useState([]); const [integration,setIntegration]=useState(null); const [form,setForm]=useState(emptyAccount); const [showForm,setShowForm]=useState(false); const [showBalances,setShowBalances]=useState(false); const [message,setMessage]=useState("");
  async function load(){const response=await apiGet(`/product/families/${familyId}/financial-accounts`);setAccounts(response.data||[]);setIntegration(response.integration);}
  useEffect(()=>{if(familyId)load().catch(e=>setMessage(e.message));},[familyId]);
  const total=useMemo(()=>accounts.reduce((sum,a)=>sum+(a.balancePaise||0),0),[accounts]);
  async function submit(event){event.preventDefault();try{await apiPost(`/product/families/${familyId}/financial-accounts`,{...form,balanceRupees:form.balanceRupees===""?null:Number(form.balanceRupees),sharedWithMemberIds:[]});setForm(emptyAccount);setShowForm(false);await load();}catch(e){setMessage(e.message);}}
  return <div className="product-page finance-page"><PageHeader eyebrow="Private by default" title="My financial overview" description="Track where family finances are spread. Exact account details remain private unless the account owner deliberately shares a summary." />
    <section className="finance-summary"><div><span>Visible balance snapshot</span><strong>{showBalances?`₹${(total/100).toLocaleString("en-IN")}`:"₹ ••••••"}</strong><small>Across {accounts.length} visible accounts</small></div><button onClick={()=>setShowBalances(!showBalances)}>{showBalances?<EyeOff/>:<Eye/>}{showBalances?"Hide":"Show"}</button></section>
    <div className="page-actions"><button className="primary-action" onClick={()=>setShowForm(!showForm)}><Plus size={17}/> Add account manually</button><button className="secondary-action" disabled title="Requires a licensed Account Aggregator partner"><Link2 size={17}/> Connect through Account Aggregator</button></div>{message&&<p className="form-message">{message}</p>}
    {integration&&<section className="privacy-note"><ShieldCheck size={20}/><div><strong>Consent-ready, not screen-scraping</strong><p>{integration.message} Nyas never asks for net-banking passwords, PINs or card credentials.</p></div></section>}
    {showForm&&<section className="product-panel"><form className="product-form" onSubmit={submit}><label>Account nickname<input required placeholder="Salary account" value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})}/></label><label>Bank / institution<input required value={form.institutionName} onChange={e=>setForm({...form,institutionName:e.target.value})}/></label><label>Type<select value={form.accountType} onChange={e=>setForm({...form,accountType:e.target.value})}>{["savings","current","fixed_deposit","loan","investment","insurance","pension","other"].map(v=><option value={v} key={v}>{v.replaceAll("_"," ")}</option>)}</select></label><label>Last four digits only<input maxLength="4" inputMode="numeric" value={form.maskedNumber} onChange={e=>setForm({...form,maskedNumber:e.target.value.replace(/\D/g,"")})}/></label><label>Current balance (optional)<input type="number" min="0" step="0.01" value={form.balanceRupees} onChange={e=>setForm({...form,balanceRupees:e.target.value})}/></label><label>Sharing<select value={form.sharingScope} onChange={e=>setForm({...form,sharingScope:e.target.value})}><option value="only_me">Only me</option><option value="family_summary">Share summary with family</option></select></label><label className="wide-field">Notes<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary-action">Save private account</button></form></section>}
    <section className="product-grid">{accounts.map(account=><article className="product-card account-card" key={account._id}><div className="card-icon"><Landmark/></div><span className="status-pill">{account.isShared?"Shared with you":account.sharingScope?.replaceAll("_"," ")}</span><h2>{account.nickname}</h2><p>{account.institutionName} • {account.accountType?.replaceAll("_"," ")}</p><strong>{showBalances&&account.balancePaise!=null?`₹${(account.balancePaise/100).toLocaleString("en-IN")}`:"₹ ••••••"}</strong><small>{account.maskedNumber?`Ending ${account.maskedNumber}`:"No account number stored"}</small></article>)}</section>
    {!accounts.length&&<div className="empty-state"><WalletCards size={34}/><h2>No accounts in your private overview</h2><p>Add only a nickname, institution and optional last four digits. Never enter credentials.</p></div>}
  </div>;
}
