import { ArrowLeft, Eye, EyeOff, ShieldCheck, Users } from "lucide-react";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { apiPost } from "../lib/api.js";

export function GetStartedPage() {
  const navigate = useNavigate(); const [mode,setMode]=useState("register"); const [form,setForm]=useState({fullName:"",phone:"",password:"",confirmPassword:""}); const [show,setShow]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event){event.preventDefault();setBusy(true);setError("");try{const path=mode==="register"?"/auth/register":"/auth/product-login";const body=mode==="register"?form:{phone:form.phone,password:form.password};const response=await apiPost(path,body);localStorage.setItem("nyasa_token",response.data.token);localStorage.setItem("nyasa_user",JSON.stringify(response.data.user));if(response.data.family?._id)localStorage.setItem("nyasa_family_id",response.data.family._id);else localStorage.removeItem("nyasa_family_id");navigate(response.data.family?._id?"/dashboard":"/families");}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <main className="login-page"><section className="login-panel product-auth-panel"><Link to="/" className="text-link"><ArrowLeft size={16}/> Back</Link><span className="brand-mark">N</span><h1>{mode==="register"?"Create your Nyas identity":"Sign in to Nyas"}</h1><p>{mode==="register"?"Your account starts without access to any family. Create a family or join through a private invitation next.":"Use your global Nyas phone and password. You can switch family spaces after signing in."}</p><div className="auth-tabs"><button className={mode==="register"?"active":""} onClick={()=>setMode("register")}>New account</button><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Existing account</button></div><form className="form-stack" onSubmit={submit}>{mode==="register"&&<label>Full name<input required minLength="2" autoComplete="name" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label>}<label>Mobile number<input required minLength="6" autoComplete="tel" inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Password<span className="password-input-wrap"><input required minLength="8" type={show?"text":"password"} autoComplete={mode==="register"?"new-password":"current-password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" className="password-visibility-button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></span></label>{mode==="register"&&<label>Confirm password<input required minLength="8" type={show?"text":"password"} autoComplete="new-password" value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})}/></label>}{error&&<p className="form-error">{error}</p>}<button disabled={busy}>{busy?"Please wait…":mode==="register"?"Create account":"Sign in"}</button></form><div className="privacy-note"><ShieldCheck/><div><strong>Family access is always separate</strong><p>Registration never adds you to the current Alahdadpur family. A steward-approved invitation or a new family space is required.</p></div></div><Link to="/login" className="text-link"><Users size={16}/> I am an existing Alahdadpur family member</Link></section></main>;
}
